phalanges:
     - geom: some_geom 
       frame_id: some_frame_id
       L_T_Cref: [1,2,3,4.5]
    
     - geom: some_other_geom 
       frame_id: some__other_frame_id
       L_T_Cref: [5,6,7,8.5]

  

  

