sensor_topics:
     - name: /thdistal_bumper/state 
       type: gazebo_msgs/ContactsState
       remap_name: thdistal/contact_state
    
     - name: /ffdistal_bumper/state 
       type: gazebo_msgs/ContactsState
       remap_name: ffdistal/contact_state



